### ISSUE TITLE
Migrate to Astro

### ISSUE THREAD

**Issue by florian-lefebvre** [anonrig/yagiz.co#49]
Hi there! I'm an Astro maintainer and I can help you migrate (following https://twitter.com/yagiznizipli/status/1734703162106224784)! Just creating this issue to track the progress

TODO
- [x] Report Astro Compiler issue
- [x] `[slug]`
	- [x] add missing components
	- [x] opengraph
	- [x] add image to head
- [x] Refactor SEO
- [x] markdown plugins
- [x] Catch up with latest commits on `main`
- [x] improve content (eg image)
- [x] rework Figure to use ImageMetadata
- [x] remove type from content entries
- [x] replace any img by Image
- [x] improve components (migrate to Astro if possible)
- [x] use adapted client directives
- [x] Setup Sentry
- [x] Update CLI
- [x] Check all routes
- [ ] Check SEO
- [x] Check TODOs
- [x] a11y audits
- [ ] Check Lighthouse
- [x] Check regressions
- [x] Check for missing repo files
- [x] README
- [x] Move from `temp` to root

**Comment by oneminch** [comment]
Hi. I'm learning Astro, so if you want some help, I can lend a hand.

**Comment by anonrig** [comment]
Maybe we can push it to a branch, and open PRs to that PR? @florian-lefebvre I can add you as a collaborator to the repository.

**Comment by florian-lefebvre** [comment]
We can do that! Let's merge the PR into a new branch and then other people can contribute

**Comment by anonrig** [comment]
@florian-lefebvre I've added you as a collaborator.

**Comment by florian-lefebvre** [comment]
I couldn't work on it lately but I have not forgotten! I'll probably wrap this up during the holidays next week

**Comment by kevinzunigacuellar** [comment]
I would like to help out too! @florian-lefebvre can you start a draft pull request I can PR to?

**Comment by florian-lefebvre** [comment]
@kevinzunigacuellar you can submit PRs against https://github.com/anonrig/yagiz.co/tree/astro-rewrite. If you don't mind, could you look into those issues specifically?

1. Check what's are best settings regarding images? Since we're using the cloudflare adapter, it cannot benefit from the sharp optimization
2. ~~`Figure.astro` does not have exactly the same dimensions as the previous `Figure.tsx`, because nextjs image applies some styles. Can you look into it to try get exactly the same dimensions?~~
3. ~~Can you check for any visual regression I may have introduced by mistake?~~

Thank you!
