### ISSUE TITLE
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by jamerrq** [anonrig/yagiz.co#76]
I wasn't able to suscribe to your newsletter due to this responses in the production site:

![image](https://github.com/anonrig/yagiz.co/assets/35697365/75cc7ffc-a168-47f2-9c45-24e6829d488b)

![image](https://github.com/anonrig/yagiz.co/assets/35697365/551d46f0-cafd-4190-8622-4cf0304a7c70)

I tried replicate the issue in local but got another one

![image](https://github.com/anonrig/yagiz.co/assets/35697365/7fca33d0-5fc5-4c0e-ac31-d56921f1fe78)

I was suspecting it was a character as my name contains an `é` but I wasn't able to find the origin even with this hint

![image](https://github.com/anonrig/yagiz.co/assets/35697365/d47e9e88-13ea-4902-99d7-3ef4032c8648)

## What else did I tried?

- A temporary mail from [Temp Mail](https://temp-mail.org/en/)

    ![image](https://github.com/anonrig/yagiz.co/assets/35697365/8687fa3f-6b97-4362-8b5e-3d67ac38d5dc)

- No tilde on my name

    ![image](https://github.com/anonrig/yagiz.co/assets/35697365/9ae12869-671b-4485-b35d-28290afb0c7d)

- No spaces

    ![image](https://github.com/anonrig/yagiz.co/assets/35697365/4228bd49-bba2-4f8b-a62c-b1d170a1e72e)

- Api and secret keys from [Mailjet](https://www.mailjet.com/), same results

**Comment by jamerrq** [comment]
I prefer sometimes try to fix instead of open the issue, but since I got no clue on this one dunno how to proceed.
If you have any hint on what could I be missing I would be happy to work on it.

In any case, have such a good day!
Thanks for all the knowledge

**Comment by anonrig** [comment]
Thank you! I'll look into it. I need to rewrite the React parts in Astro anyways...
